# Generated by Django 3.1.2 on 2021-08-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
